---
apiVersion: v1
kind: Service
metadata:
  name: blogapp-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8081
      targetPort: 8081
  selector:
    name: blogapp