---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blogapp
spec:
  replicas: 2
  selector:
    matchLabels:
      name: blogapp
  template:
    metadata:
      labels:
        name: blogapp
    spec:
      containers:
        - name: application
          image: username/blog
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: dockerhub-secret
          env:
            - name: POSTGRES_DB
              value: blog
            - name: POSTGRES_USER
              value: blog
            - name: POSTGRES_PASSWORD
              value: blog
            - name: POSTGRES_HOST
              value: postgresql:5432
          ports:
            - containerPort: 8081